### ISSUE TITLE
Error: comentario mal formado

### ISSUE THREAD

**Issue by JavierGF00** [iesgrancapitan-entornos/practica-5-github-issues-R4f4Lc#1]
Sustituye las dos barras por un #

https://github.com/iesgrancapitan-entornos/practica-5-github-issues-R4f4Lc/blob/6df38549f550c72dac53182ed4fbe5b14c03b1a7/hola_mundo.py#L1

**Comment by R4f4Lc** [comment]
Vale voy a sustituirlo y me dices si está bien modificado

**Comment by JavierGF00** [comment]
De acuerdo

**Comment by R4f4Lc** [comment]
Vale ya está arreglado comprueba

**Comment by JavierGF00** [comment]
Bien hecho

**Comment by R4f4Lc** [comment]
Cierro issue
